kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
kotlin.native.cacheKind=none
kotlin.mpp.applyDefaultHierarchyTemplate=false
org.gradle.internal.http.connectionTimeout=100000
org.gradle.internal.http.socketTimeout=100000

# P0 uses Skia first to isolate shared Compose rendering from ArkUI interop.
rendererBackend=skia
ohosSkikoVersion=0.9.22.2-1.0.0
