name: Nightly Builds

on:
  push:
    branches:
      - 'release/**'
      - master
    tags:
      - '*'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/my-build-action.yml
    if: startsWith(github.ref, 'refs/heads')
    with:
      name: 'Nightly Builds'
    secrets: inherit
  build_minified_release:
    uses: ./.github/workflows/my-build-action.yml
    if: startsWith(github.ref, 'refs/heads/')
    with:
      name: 'Minified Builds'
      minify: true
      nightly_release: true
    secrets: inherit
  build_minified_pr:
    uses: ./.github/workflows/my-build-action.yml
    if: github.event_name == 'pull_request'
    with:
      name: 'Minified PR Builds'
      minify: true
      nightly_release: false
    secrets: inherit
  release:
    uses: ./.github/workflows/my-build-action.yml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    with:
      name: 'Release'
      release: true
      minify: true
    secrets: inherit
